version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Then connect to localhost:5000

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - app-tier


  python_app:
    build:
      context: ./src      
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
